// SPDX-License-Identifier: Apache-2.0

package com.androidplot;

import android.graphics.Canvas;
import androidx.annotation.NonNull;

/**
 * Defines methods used for monitoring events generated by a Plot.
 */
public interface PlotListener {

    /**
     * Fired immediately before the Plot "source" is drawn onto canvas.
     * Commonly used by implementing Series instances to activate a read
     * lock on it's self in preparation for the Plot's imminent reading
     * of that series.
     * @param source
     * @param canvas
     */
    void onBeforeDraw(@NonNull Plot source, @NonNull Canvas canvas);

    /**
     * Fired immediately after the Plot "source" is drawn onto canvas.
     * Just as onBeforeDraw(...) is commonly used by Series implementations
     * to activate a read lock, this method is commonly used to release that
     * same lock.
     * @param source
     * @param canvas
     */
    void onAfterDraw(@NonNull Plot source, @NonNull Canvas canvas);
}
