// SPDX-License-Identifier: Apache-2.0

package com.androidplot.xy;

/**
 * An immutable object generated by XYStepCalculator representing
 * a stepping model to be used by an XYPlot.
 */
public class Step {

    private final double stepCount;
    private final double stepPix;
    private final double stepVal;

    //public XYStep() {}

    public Step(double stepCount, double stepPix, double stepVal) {
        this.stepCount = stepCount;
        this.stepPix = stepPix;
        this.stepVal = stepVal;
    }

    public double getStepCount() {
        return stepCount;
    }

    /*public void setStepCount(double stepCount) {
        this.stepCount = stepCount;
    }*/

    public double getStepPix() {
        return stepPix;
    }

    /*public void setStepPix(float stepPix) {
        this.stepPix = stepPix;
    }*/

    public double getStepVal() {
        return stepVal;
    }

    /*public void setStepVal(double stepVal) {
        this.stepVal = stepVal;
    }*/
}
