// SPDX-License-Identifier: Apache-2.0

buildscript {
    repositories {
        google()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.4'
    }
}

apply plugin: 'com.android.application'

android {
    compileSdkVersion theCompileSdkVersion
    buildToolsVersion theBuildToolsVersion

    defaultConfig {
        applicationId "com.androidplot.demo.wearable"
        minSdkVersion 20
        targetSdkVersion theTargetSdkVersion
        versionCode theVersionCode
        versionName theVersionName
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile project(':androidplot-core')
    compile 'com.google.android.support:wearable:2.3.0'
    compile 'com.google.android.gms:play-services-wearable:8.3.0'
}
