name: build androidplot
on:
  push:
    branches:
      - v1.5.10b # TODO change to master
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        env:
          FOO: "somestuff"
        run: echo "abcdefg" | base64 -d > foo.txt
      - shell: bash
        env:
          ENCODED_KEYSTORE: ${{secrets.DEMOAPP_SIGNING_KEY}}
        run: echo $ENCODED_KEYSTORE | sed 's/ /\n/g' | base64 –d > signing.keystore
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Build and Test
        run: ./gradlew testDebugUnitTest jacocoTestDebugUnitTestReport
      - name: Build Release
        run: ./gradlew assembleRelease
      - name: Javadoc
        run: ./gradlew javadoc
      - name: Code Coverage
        run: bash <(curl -s https://codecov.io/bash)