name: build androidplot
on:
  push:
    branches:
      - v1.5.10b # TODO change to master
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        env:
          ENCODED_KEYSTORE: ${{ secrets.DEMOAPP_SIGNING_KEY }}
        run: |
          "$env:ENCODED_KEYSTORE" | base64 --decode >> keystore.jks
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Build and Test
        run: ./gradlew testDebugUnitTest jacocoTestDebugUnitTestReport
      - name: Build Release
        run: ./gradlew assembleRelease
      - name: Javadoc
        run: ./gradlew javadoc
      - name: Code Coverage
        run: bash <(curl -s https://codecov.io/bash)